branch-defaults:
  local:
    environment: test
  master:
    environment: prod
global:
  application_name: landerds-app
  default_ec2_keyname: BuildcaveKeyPair
  default_platform: 64bit Amazon Linux 2016.03 v2.1.0 running Docker 1.9.1
  default_region: us-west-2
  profile: null
  sc: git
deploy:
  artifact: "built.zip"